import Head from 'next/head'
import Link from 'next/link'
// import styles from '../styles/Home.module.css'
import {createClient} from 'contentful'


const client = createClient({
  space: process.env.CONTENTFUL_SPACE_ID,
  accessToken: process.env.CONTENTFUL_ACCESS_TOKEN
});

// This function will access the contentful and pass its value as props to the Home function
export async function getStaticProps(){
  
  let data = await client.getEntries({
    // This query will get all the content from Article (always add it in lower case) that we saved in the Content Model in Contentful 
    content_type: 'article'
  })
  return({
    props:{
      articles:data.items
    }
  })
}

// props being destructured into {articles}
export default function Home({articles}) {
  console.log(articles)
  return (
    <>
    {/* <div className={styles.container}> */}
      <Head>
        <title>Next.js Blog App</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <main className={styles.main}> */}
      <main>
      <ul>
        {articles.map(article => (
          // sys.id is a unique id generated by contentful
          <li key={article.sys.id}>
        
            <Link href={"/articles/" + article.fields.slug}> 
              <a> {article.fields.title}</a>
            </Link>
          </li>
        ))}
      </ul>
      </main>

      {/* <footer className={styles.footer}> */}
      <footer>
      </footer>
    {/* </div> */}
    </>
  )
}
